FROM python:3.11.2

RUN pip install openai==0.28.0 openai-whisper==20230918 pyTelegramBotAPI==4.13.0

RUN apt-get update && apt-get install -y ffmpeg

RUN pip install pandas==2.1.0 tabulate==0.9.0 pymongo==4.5.0 seaborn==0.13.0

WORKDIR /NL_to_table

COPY src/* /NL_to_table/

COPY text/* /NL_to_table/text/

COPY config/data_structure.json /NL_to_table/config/

COPY user_data/dummy_data.csv /NL_to_table/user_data/

COPY version.txt /NL_to_table/

CMD python main.py
