FROM python:3.11

RUN pip install openai openai-whisper pyTelegramBotAPI

RUN apt-get update && apt-get install -y ffmpeg

RUN pip install pandas tabulate pymongo seaborn

WORKDIR /NL_to_table

COPY src/* /NL_to_table/

COPY text/* /NL_to_table/text/

COPY config/data_structure.json /NL_to_table/config/

COPY user_data/dummy_data.csv /NL_to_table/user_data/

COPY version.txt /NL_to_table/

CMD python main.py
